services:
  anvil:
    build: .
    ports:
      - "8546:8545"
    command: scripts/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8545'"]
      interval: 2s
      timeout: 1s
      retries: 10
  test:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - ETH_HTTP_URL=http://anvil:8545
    depends_on:
      anvil:
        condition: service_healthy
    command: python -m pytest tests/ -v
  dev:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: bash
    profiles:
      - dev
    stdin_open: true
    tty: true
