def is_operator_set_quorum(): pass
def get_slashable_stake_look_ahead_per_quorum(): pass
def get_stake_type_per_quorum(): pass
def get_strategy_params_at_index(): pass
def get_minimum_stake_for_quorum(): pass
def get_total_stake_indices_at_block_number(): pass
def get_total_stake_at_block_number_from_index(): pass
def get_total_stake_update_at_index(): pass
def get_current_total_stake(): pass
def get_total_stake_history_length(): pass
def get_stake_at_block_number_and_index(): pass
def get_operator_stake_in_quorums_of_operator_at_current_block(): pass
def weight_of_operator_for_quorum(): pass
def strategy_params_length(): pass
def strategy_params_by_index(): pass
def get_stake_history_length(): pass
def get_stake_history(): pass
def get_latest_stake_update(): pass
def get_stake_update_at_index(): pass
def get_stake_at_block_number(): pass
def get_stake_update_index_at_block_number(): pass
def get_stake_at_block_number_and_index(): pass
def get_strategy_per_quorum_at_index(): pass