def test_get_allocatable_magnitude(): pass
def test_get_max_magnitudes(): pass
def test_get_allocation_info(): pass
def test_get_operator_sets_for_operator(): pass
def test_get_allocation_delay(): pass
def test_get_registered_sets(): pass
def test_is_operator_registered_with_operator_set(): pass
def test_is_operator_slashable(): pass
def test_get_allocated_stake(): pass
def test_get_operators_for_operator_set(): pass
def test_get_num_operators_for_operator_set(): pass
def test_get_strategies_for_operator_set(): pass
def test_get_avs_registrar(): pass
def test_get_operator_details(): pass
def test_get_encumbered_magnitude(): pass
def test_get_deallocation_delay(): pass
def test_get_allocation_configuration_delay(): pass
def test_get_num_operator_sets_for_operator(): pass
def test_get_slashable_shares(): pass
def test_get_slashable_shares_for_operator_sets_before(): pass
