def test_get_operator_shares(): pass
def test_is_operator_registered(): pass
def test_get_staker_shares(): pass
def test_get_delegated_operator(): pass
def test_get_operator_details(): pass
def test_get_operator_shares_in_strategy(): pass
def test_calculate_delegation_approval_digest_hash(): pass
def test_get_operators_shares(): pass
def test_get_delegation_approver_salt_is_spent(): pass
def test_get_pending_withdrawal_status(): pass
def test_get_cumulative_withdrawals_queued(): pass
