name: Build and Test

on:
  push:
    branches: [ if3-dev ]
  pull_request:
    branches: [ if3-dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Docker images
        run: make build
        
      - name: Start Anvil
        run: docker compose up -d anvil
        
      - name: Wait for Anvil to be ready
        run: |
          echo "Waiting for Anvil to be ready..."
          sleep 20
        
      - name: Run Tests
        run: make test
          
      - name: Cleanup
        if: always()
        run: make down 