name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: make rebuild

      - name: Start Anvil and Run Tests
        run: make test

      - name: Run linting
        run: make lint
        
      - name: Run type checking
        run: make mypy 

      - name: Check formatting
        run: make format-check

      - name: Cleanup
        if: always()
        run: make down
