name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and run tests
        run: |
          docker compose build
          docker compose up -d ganache
          sleep 5  # Give Ganache time to start
          docker compose run test

      - name: Check formatting
        run: docker compose run format --check .

      - name: Run linting
        run: docker compose run lint
        
      - name: Run type checking
        run: docker compose run mypy 