name: Test

on:
  push:
    branches: [ if3-dev ]
  pull_request:
    branches: [ if3-dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Basic Tests (No Anvil dependency)
        run: make basic-test
        
      - name: Run Full Tests with Anvil
        run: |
          # Start Anvil in the background
          make anvil-reset &
          # Wait for Anvil to be ready
          sleep 15
          # Run full test suite
          make test 